# Generated by Django 5.1.3 on 2024-12-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
